import { createReadStream } from 'node:fs';
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { Readable } from 'node:stream';

import type { FileStorage } from './types.ts';

/**
 * Writes uploads to a directory on disk. Used in local development so the app runs with
 * no cloud account and no S3 emulator.
 */
export class LocalFileStorage implements FileStorage {
  readonly driver = 'local' as const;

  private readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  /**
   * Resolves a storage key inside the upload root, refusing anything that escapes it.
   *
   * Keys are generated by the server from a UUID and never contain user input, so this
   * should be unreachable. It stays because the consequence of being wrong is arbitrary
   * file write outside the upload directory, and a guard that costs two lines is worth
   * having between an attacker and the filesystem.
   */
  private resolvePath(key: string): string {
    const resolved = path.resolve(this.root, key);
    const relative = path.relative(this.root, resolved);

    if (relative.startsWith('..') || path.isAbsolute(relative)) {
      throw new Error(`Storage key escapes the upload root: ${key}`);
    }
    return resolved;
  }

  async put(key: string, body: Buffer, _contentType: string): Promise<void> {
    const target = this.resolvePath(key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, body);
  }

  // `async` deliberately: a rejected key must surface as a rejected promise, matching
  // the interface's contract, not as a synchronous throw the caller never expected.
  async getStream(key: string): Promise<Readable> {
    return createReadStream(this.resolvePath(key));
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolvePath(key), { force: true });
  }

  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.resolvePath(key));
      return true;
    } catch {
      return false;
    }
  }

  /** Local files are served by the API itself, so there is no direct URL to hand out. */
  getSignedUrl(): Promise<string | null> {
    return Promise.resolve(null);
  }
}
